spring.application.name=PariVaar
server.port=8080

# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://ep-purple-smoke-a7b15sq7.ap-southeast-2.aws.neon.tech:5432/parivaarDb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8YGOsrRFMo2U

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect