spring.application.name=PariVaar
server.port=8080

spring.config.import=optional:file:.env[.properties],optional:file:PariVaar/.env[.properties]

# PostgreSQL datasource configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google OAuth2 Credentials
google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000